/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.StackController;

/**
 *
 * @author Marcelo Guzmán
 */
public class QuestionForm extends javax.swing.JDialog {
    StackController stackController;
    /**
     * Creates new form QuestionForm
     */
    public QuestionForm(java.awt.Frame parent, boolean modal, StackController stackController) {
        super(parent, modal);
        initComponents();
        this.stackController = stackController;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formLayeredPane = new javax.swing.JLayeredPane();
        firstFormPanel = new javax.swing.JPanel();
        formTitle1Lbl = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        questionLbl = new javax.swing.JLabel();
        qContentScrollPane = new javax.swing.JScrollPane();
        qContentTxtArea = new javax.swing.JTextArea();
        continueBtn = new javax.swing.JButton();
        labelsFormPanel = new javax.swing.JPanel();
        formTitle2Lbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("StackOverflow");

        formLayeredPane.setLayout(new java.awt.CardLayout());

        firstFormPanel.setPreferredSize(new java.awt.Dimension(397, 302));

        formTitle1Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        formTitle1Lbl.setText("Crear una pregunta");

        titleField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setText("Titulo");

        questionLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionLbl.setText("Pregunta");

        qContentTxtArea.setColumns(20);
        qContentTxtArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qContentTxtArea.setLineWrap(true);
        qContentTxtArea.setRows(5);
        qContentScrollPane.setViewportView(qContentTxtArea);

        continueBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        continueBtn.setText("Continuar");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstFormPanelLayout = new javax.swing.GroupLayout(firstFormPanel);
        firstFormPanel.setLayout(firstFormPanelLayout);
        firstFormPanelLayout.setHorizontalGroup(
            firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formTitle1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(firstFormPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(questionLbl))
                        .addGap(20, 20, 20)
                        .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qContentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(titleField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstFormPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(continueBtn)))
                .addContainerGap())
        );
        firstFormPanelLayout.setVerticalGroup(
            firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formTitle1Lbl)
                .addGap(18, 18, 18)
                .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLbl)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionLbl)
                    .addComponent(qContentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(continueBtn)
                .addGap(18, 18, 18))
        );

        formLayeredPane.add(firstFormPanel, "card2");

        formTitle2Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        formTitle2Lbl.setText("Elegir Etiquetas");

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setText("Volver");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout labelsFormPanelLayout = new javax.swing.GroupLayout(labelsFormPanel);
        labelsFormPanel.setLayout(labelsFormPanelLayout);
        labelsFormPanelLayout.setHorizontalGroup(
            labelsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelsFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(labelsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formTitle2Lbl)
                    .addComponent(backBtn))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        labelsFormPanelLayout.setVerticalGroup(
            labelsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelsFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formTitle2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        formLayeredPane.add(labelsFormPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formLayeredPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formLayeredPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        moveToFront(formLayeredPane, labelsFormPanel);
    }//GEN-LAST:event_continueBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        moveToFront(formLayeredPane, firstFormPanel);
    }//GEN-LAST:event_backBtnActionPerformed
    
    private void moveToFront(javax.swing.JLayeredPane layerPane, javax.swing.JPanel panel){
        layerPane.removeAll();
        layerPane.add(panel);
        layerPane.repaint();
        layerPane.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton continueBtn;
    private javax.swing.JPanel firstFormPanel;
    private javax.swing.JLayeredPane formLayeredPane;
    private javax.swing.JLabel formTitle1Lbl;
    private javax.swing.JLabel formTitle2Lbl;
    private javax.swing.JPanel labelsFormPanel;
    private javax.swing.JScrollPane qContentScrollPane;
    private javax.swing.JTextArea qContentTxtArea;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
