/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.StackController;
import Model.Label;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcelo Guzmán
 */
public class QuestionForm extends javax.swing.JDialog {
    StackController stackController;
    ArrayList<Label> labels = new ArrayList<>();
    boolean labelsDisplayed;
    StartFrame parent;
    /**
     * Creates new form QuestionForm
     */
    public QuestionForm(java.awt.Frame parent, boolean modal, StackController stackController) {
        super(parent, modal);
        initComponents();
        labelsDisplayed = false;
        this.parent = (StartFrame) parent;
        this.stackController = stackController;
        
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        successDialog = new javax.swing.JDialog();
        successLbl = new javax.swing.JLabel();
        backToStartBtn = new javax.swing.JButton();
        formPanel = new javax.swing.JPanel();
        firstFormPanel = new javax.swing.JPanel();
        formTitle1Lbl = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        questionLbl = new javax.swing.JLabel();
        qContentScrollPane = new javax.swing.JScrollPane();
        qContentTxtArea = new javax.swing.JTextArea();
        continueBtn = new javax.swing.JButton();
        addLabelsCheckBtn = new javax.swing.JRadioButton();
        labelsFormPanel = new javax.swing.JPanel();
        formTitle2Lbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelsContainer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelDescriptionTxtArea = new javax.swing.JTextArea();
        postBtn = new javax.swing.JButton();

        successDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        successDialog.setTitle("StackOverflow");
        successDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        successLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        successLbl.setText("Pregunta registrada con exito");

        backToStartBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backToStartBtn.setText("Volver");
        backToStartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToStartBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout successDialogLayout = new javax.swing.GroupLayout(successDialog.getContentPane());
        successDialog.getContentPane().setLayout(successDialogLayout);
        successDialogLayout.setHorizontalGroup(
            successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, successDialogLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(successLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(successDialogLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(backToStartBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        successDialogLayout.setVerticalGroup(
            successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successDialogLayout.createSequentialGroup()
                .addComponent(successLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backToStartBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("StackOverflow");

        formPanel.setLayout(new java.awt.CardLayout());

        firstFormPanel.setPreferredSize(new java.awt.Dimension(397, 302));

        formTitle1Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        formTitle1Lbl.setText("Crear una pregunta");

        titleField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setText("Titulo");

        questionLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionLbl.setText("Pregunta");

        qContentTxtArea.setColumns(20);
        qContentTxtArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qContentTxtArea.setLineWrap(true);
        qContentTxtArea.setRows(5);
        qContentScrollPane.setViewportView(qContentTxtArea);

        continueBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        continueBtn.setText("Continuar");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });

        addLabelsCheckBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addLabelsCheckBtn.setText("Agregar Etiquetas");
        addLabelsCheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLabelsCheckBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstFormPanelLayout = new javax.swing.GroupLayout(firstFormPanel);
        firstFormPanel.setLayout(firstFormPanelLayout);
        firstFormPanelLayout.setHorizontalGroup(
            firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formTitle1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(firstFormPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstFormPanelLayout.createSequentialGroup()
                                .addComponent(addLabelsCheckBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addComponent(continueBtn))
                            .addGroup(firstFormPanelLayout.createSequentialGroup()
                                .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(questionLbl))
                                .addGap(20, 20, 20)
                                .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(qContentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(titleField))))))
                .addGap(18, 18, 18))
        );
        firstFormPanelLayout.setVerticalGroup(
            firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formTitle1Lbl)
                .addGap(18, 18, 18)
                .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLbl)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionLbl)
                    .addComponent(qContentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(firstFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continueBtn)
                    .addComponent(addLabelsCheckBtn))
                .addGap(18, 18, 18))
        );

        formPanel.add(firstFormPanel, "card1");

        formTitle2Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        formTitle2Lbl.setText("Elegir Etiquetas");

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setText("Volver");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        labelsContainer.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(labelsContainer);

        labelDescriptionTxtArea.setColumns(20);
        labelDescriptionTxtArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDescriptionTxtArea.setLineWrap(true);
        labelDescriptionTxtArea.setRows(5);
        jScrollPane2.setViewportView(labelDescriptionTxtArea);

        postBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        postBtn.setText("Publicar Pregunta");
        postBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout labelsFormPanelLayout = new javax.swing.GroupLayout(labelsFormPanel);
        labelsFormPanel.setLayout(labelsFormPanelLayout);
        labelsFormPanelLayout.setHorizontalGroup(
            labelsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelsFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(labelsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(labelsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(formTitle2Lbl)
                        .addComponent(backBtn)))
                .addGroup(labelsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(labelsFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(labelsFormPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(postBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        labelsFormPanelLayout.setVerticalGroup(
            labelsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelsFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formTitle2Lbl)
                .addGap(18, 18, 18)
                .addGroup(labelsFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(labelsFormPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(labelsFormPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(postBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(backBtn)
                .addContainerGap())
        );

        formPanel.add(labelsFormPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        if(addLabelsCheckBtn.isSelected()){
            
            java.awt.CardLayout cl = (java.awt.CardLayout) formPanel.getLayout();
            cl.show(formPanel, "card2");
           
            if(!labelsDisplayed){
                labelsDisplayed = true;
                ArrayList<Label> stackLabels = stackController.getLabels();
                for(Label l : stackLabels){
                    JRadioButton labelSelectBtn = new JRadioButton(l.getName());
                    labelSelectBtn.setFont(new java.awt.Font("Tahoma", 0, 14));
                    labelSelectBtn.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                labelSelectedActionPerformed(evt, labelSelectBtn);
                            }
                        });
                    labelsContainer.add(labelSelectBtn);
                }
            }
            
        }
        else{
            makeQuestion();
        }
    }//GEN-LAST:event_continueBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) formPanel.getLayout();
        cl.show(formPanel, "card1");
    }//GEN-LAST:event_backBtnActionPerformed

    private void addLabelsCheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLabelsCheckBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addLabelsCheckBtnActionPerformed

    private void backToStartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToStartBtnActionPerformed
        successDialog.dispose();
        this.dispose();
    }//GEN-LAST:event_backToStartBtnActionPerformed
       
    
    private void postBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postBtnActionPerformed

        for(Component c : labelsContainer.getComponents()){
            JRadioButton labelBtn = (JRadioButton) c;
            if(labelBtn.isSelected()){
                labels.add(stackController.getLabel(labelBtn.getText()));
            }
        }
        
        makeQuestion();
    }//GEN-LAST:event_postBtnActionPerformed
    
    private void labelSelectedActionPerformed(java.awt.event.ActionEvent evt, javax.swing.JRadioButton labelCheckButton){
        labelDescriptionTxtArea.setText(stackController.getLabel(labelCheckButton.getText()).getDescription());
    }
    
    private void makeQuestion(){
        
        DefaultTableModel model = (DefaultTableModel) parent.getQuestionsTable().getModel();
            
            if(model.getRowCount()==0){
                javax.swing.JPanel container2 = parent.getContainer2();
                container2.removeAll();
                container2.add(parent.getQuestionsScrollPane());
                container2.repaint();
                container2.revalidate();
            }
            
            stackController.ask(titleField.getText(), qContentTxtArea.getText(), labels.isEmpty()? null : labels);
            
            successDialog.pack();
            successDialog.setLocationRelativeTo(null);
            
            Model.Question question = stackController.getLastQuestion();
            
            String date = stackController.setDateFormat(question.getPostDate(), "dd/MM/yyyy");
            Object[] newRow = {question.getTitle(), question.getAuthor(), question.getAnswersCount(), date};
            model.addRow(newRow);
            
            // Hacemos visible el mensaje informando que la pregunta se registra correctamente
            successDialog.setVisible(true);
    }
    

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addLabelsCheckBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backToStartBtn;
    private javax.swing.JButton continueBtn;
    private javax.swing.JPanel firstFormPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel formTitle1Lbl;
    private javax.swing.JLabel formTitle2Lbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea labelDescriptionTxtArea;
    private javax.swing.JPanel labelsContainer;
    private javax.swing.JPanel labelsFormPanel;
    private javax.swing.JButton postBtn;
    private javax.swing.JScrollPane qContentScrollPane;
    private javax.swing.JTextArea qContentTxtArea;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JDialog successDialog;
    private javax.swing.JLabel successLbl;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
