/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.StackController;
import Errors.InsufficientReputationException;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelo Guzmán
 */
public class RewardQuestionForm extends javax.swing.JDialog {
    StackController stackController;
    QuestionView parent;
    boolean firstFocused = true;
    /**
     * Creates new form RewardQuestionForm
     */
    public RewardQuestionForm(JDialog parent, boolean modal, StackController stackController) {
        super(parent, modal);
        initComponents();
        this.parent = (QuestionView) parent;
        this.stackController = stackController;
        setLocationRelativeTo(null);
        backBtn.requestFocus();
        
        rewardAmountTxtField.addFocusListener(new FocusAdapter(){
            @Override
            public void focusGained(FocusEvent e){
                if(firstFocused){
                    rewardAmountTxtField.setText("");
                    firstFocused = false;
                }
            }

        });
        // Actualizamos la recompensa hasta el momento
        actualRewardLbl.setText(Integer.toString(this.parent.getQuestion().getReward()));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        successDialog = new javax.swing.JDialog();
        successMsgLbl = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        text1Lbl = new javax.swing.JLabel();
        actualRewardLbl = new javax.swing.JLabel();
        text2Lbl = new javax.swing.JLabel();
        rewardAmountTxtField = new javax.swing.JTextField();
        sendRewardBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        successDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        successDialog.setTitle("StackOverflow - Éxito");
        successDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        successMsgLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        successMsgLbl.setText("Pregunta recompensada!");

        closeBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closeBtn.setText("Volver");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout successDialogLayout = new javax.swing.GroupLayout(successDialog.getContentPane());
        successDialog.getContentPane().setLayout(successDialogLayout);
        successDialogLayout.setHorizontalGroup(
            successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successDialogLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(closeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, successDialogLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(successMsgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        successDialogLayout.setVerticalGroup(
            successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(successMsgLbl)
                .addGap(18, 18, 18)
                .addComponent(closeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        text1Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        text1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1Lbl.setText("Esta pregunta posee una recompensa de ");

        actualRewardLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        actualRewardLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualRewardLbl.setText("PUNTOS");

        text2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        text2Lbl.setText("Ingrese la recompensa que desea agregar");

        rewardAmountTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rewardAmountTxtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rewardAmountTxtField.setText("PUNTOS");
        rewardAmountTxtField.setToolTipText("Ingrese la recompensa");

        sendRewardBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sendRewardBtn.setText("Enviar Recompensa");
        sendRewardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRewardBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backBtn.setText("Volver");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(actualRewardLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(text1Lbl)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rewardAmountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(sendRewardBtn))
                                .addComponent(text2Lbl, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualRewardLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(text2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rewardAmountTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendRewardBtn))
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void sendRewardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRewardBtnActionPerformed
        Integer rewardAmount;
        
        try{
            rewardAmount = Integer.parseInt(rewardAmountTxtField.getText());
            try {
                stackController.reward(parent.getQuestion(), rewardAmount);
                
                // Actualizar recompensas en vista principal y vista de la pregunta
                parent.getRewardAmountLbl().setText(Integer.toString(parent.getQuestion().getReward()));
                parent.getParent().getReputationLbl().setText(Integer.toString(stackController.getOnlineUser().getReputation()));
                
                successDialog.setLocationRelativeTo(null);
                successDialog.pack();
                successDialog.setVisible(true);
            } catch (InsufficientReputationException ex) {
                JOptionPane.showMessageDialog(parent, ex.getMessage());
            }
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido, por favor.");
        }
        
        
    }//GEN-LAST:event_sendRewardBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        successDialog.dispose();
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualRewardLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField rewardAmountTxtField;
    private javax.swing.JButton sendRewardBtn;
    private javax.swing.JDialog successDialog;
    private javax.swing.JLabel successMsgLbl;
    private javax.swing.JLabel text1Lbl;
    private javax.swing.JLabel text2Lbl;
    // End of variables declaration//GEN-END:variables
}
